trigger:
  branches:
    include:
      - dev
      - main
      - feature/*
      - release/*
      - hotfix/*
pr:
  autoCancel: true
  branches:
    include:
      - dev

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'dotnet install'
  inputs:
    packageType: 'sdk' # Options: runtime, sdk
    version: '2.2.100'

- powershell: '.\build.ps1 -t AzureDevOps' 
  displayName: 'cake build'